# Generated by Django 5.2.6 on 2025-10-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamspace", "0003_alter_user_available_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projects",
            name="matching_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projects",
            name="recruitment_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projects",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
