# Generated by Django 5.2.6 on 2025-10-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamspace", "0006_alter_user_available_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="major",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PROGRAMMING", "개발/프로그래밍"),
                    ("DATA_AI", "데이터/AI"),
                    ("SECURITY_NET", "보안/네트워크"),
                    ("DESIGN", "디자인/기획"),
                    ("NON_MAJOR", "비전공자/기타"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
