# Generated by Django 5.2.6 on 2025-11-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamspace", "0010_projectapplicants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchscores",
            name="explanation",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
