# Generated by Django 5.2.6 on 2025-11-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamspace", "0012_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplicants",
            name="status",
            field=models.CharField(
                choices=[
                    ("검토 대기", "Pending Review"),
                    ("검토 완료", "Reviewed"),
                    ("승인", "Accepted"),
                    ("거절", "Rejected"),
                ],
                default="검토 대기",
                max_length=10,
            ),
        ),
    ]
