# Generated by Django 5.2.6 on 2025-11-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamspace", "0013_projectapplicants_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplicants",
            name="available_time",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="projectapplicants",
            name="motivation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectapplicants",
            name="role",
            field=models.CharField(default="N/A", max_length=100),
        ),
    ]
