# Generated by Django 5.2.6 on 2025-10-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamspace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="available_region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SEOUL", "수도권"),
                    ("CHUNGCHEONG", "충청권"),
                    ("YEONGNAM", "영남권"),
                    ("HONAM", "호남권"),
                    ("ETC", "기타"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
