# Generated by Django 5.2.6 on 2025-10-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamspace", "0002_alter_user_available_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="available_region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
