# Generated by Django 5.2.6 on 2025-10-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamspace", "0004_projects_end_date_projects_matching_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchscores",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
