# Generated by Django 4.2 on 2025-10-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamspace", "0005_matchscores_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="available_region",
            field=models.TextField(blank=True, null=True),
        ),
    ]
