# Generated by Django 5.2.6 on 2025-10-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamspace", "0007_alter_user_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchscores",
            name="experience_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="matchscores",
            name="personality_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="matchscores",
            name="tech_score",
            field=models.IntegerField(default=0),
        ),
    ]
