# Generated by Django 5.2.6 on 2025-10-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamspace", "0008_matchscores_experience_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
