# Generated by Django 5.2.6 on 2025-11-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamspace', '0010_projectapplicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('active', '진행중'), ('completed', '완료'), ('draft', '임시저장')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tech_stack',
            field=models.JSONField(default=list),
        ),
    ]
