# Generated by Django 5.2.6 on 2025-11-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamspace', '0012_auto_20251102_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicants',
        ),
    ]
